IMPORT LIBRARIES

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score, recall_score,f1_score,roc_curve, roc_auc_score
from sklearn import svm
import csv

In [2]:
np.random.seed(187)

LOAD DATA

In [3]:
df = pd.read_csv('Train.csv')

In [4]:
df.head()

,ID,lon,lat,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,48.203643,40.090329,0,-23.328630,-16.733172,1599,1897,4129,4075,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,49.022098,39.829817,0,-18.638613,-10.334208,1907,2090,2953,3059,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,48.752963,39.764330,0,-21.356376,-14.257931,1355,1719,6722,6528,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,48.788806,39.770708,0,-20.289892,-9.187885,1504,1657,2093,2040,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,48.195468,39.857486,0,-19.046569,-14.159119,1357,1740,4905,4796,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972


In [ ]:
#print(df.head(10))

EDA and STATS:  Done in R, ande in Python too

PREPROCESSING

In [5]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [6]:
df1.head()

,ID,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,re1_01,re2_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,0,-23.328630,-16.733172,1599,1897,4129,4075,2456,3594,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,0,-18.638613,-10.334208,1907,2090,2953,3059,2662,2777,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,0,-21.356376,-14.257931,1355,1719,6722,6528,2324,5405,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,0,-20.289892,-9.187885,1504,1657,2093,2040,1902,1914,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,0,-19.046569,-14.159119,1357,1740,4905,4796,2409,4150,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972


MORE EDA FIRST

In [7]:
#determine variable types
df1.dtypes

,0
ID,object
label,int64
VH_01,float64
VV_01,float64
blue_01,int64
...,...
re2_12,int64
re3_12,int64
red_12,int64
swir1_12,int64


In [8]:
#change label to category (same as factor in R)
df1['label']= df1['label'].astype("category")

In [9]:
df1.dtypes

,0
ID,object
label,category
VH_01,float64
VV_01,float64
blue_01,int64
...,...
re2_12,int64
re3_12,int64
red_12,int64
swir1_12,int64


## Propsed Steps from here:
 Train Test Split of Train.csv

 StandardScaler on this 'train' data

 PCA on Scaled

 Modeling with this PCA

 Confusion Matrix/F1Score/AUC of model

 Run Model on this 'test' data

 Check multiple model types

 Then run on Test.csv and submit!



BACK TO PREPROCESSING

In [ ]:
#Train Test Split on df1

In [10]:
#first define
X = df1.drop(['label'], axis=1)
y = df1['label']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=187)

In [12]:
# except label, take all columns
cols = X_train.columns.difference(['ID', 'label'])

In [13]:
#STANDARDSCALER

sc = StandardScaler()

# normalise only selected columns
X_train[cols] = sc.fit_transform(X_train[cols])

In [14]:
print(X_train)

               ID     VH_01     VV_01   blue_01  green_01    nir_01   nira_01  \
410  ID_TR_K9QM3P  0.391338  0.459898  0.538248  0.177820  0.345993  0.451430   
819  ID_TR_NN16UX  0.076397  1.136580  1.728600  1.652411  0.820518  0.797256   
888  ID_TR_SQ0P82  0.742511  0.475065  0.977589  0.664522  0.238576  0.187045   
10   ID_TR_9XUY41  0.667970  0.039622  0.061357  0.186511  1.524043  1.717883   
221  ID_TR_NF313F  0.598050  0.652943 -0.073825 -0.329162  0.530137  0.616671   
..            ...       ...       ...       ...       ...       ...       ...   
650  ID_TR_RMHRCN  0.012720  0.610762  1.319299  1.855203  1.534667  1.558544   
79   ID_TR_P6VZ41 -0.637186 -0.628189 -0.468106 -0.442146  0.791008  0.800797   
466  ID_TR_OT8HLJ -0.596981 -2.020168 -1.189076 -0.876701 -0.721098 -0.974363   
286  ID_TR_9V20YA -0.626076  0.592615 -0.791040 -0.824555 -0.267820 -0.057276   
619  ID_TR_Q6WW8Y  1.737251  1.395407 -0.528186 -0.456631 -0.004589 -0.083242   

       re1_01    re2_01    

PCA on X_train (and save for re-use on X_test)

In [ ]:
#start with test train split

#X= df1.drop['label']
#y=df1['label']

#need to make sure i get the variables to include in X and y correc, what about ID?


In [ ]:
#X_train, X_test,
#y_train, y_test = train_test_split(X,y ,
#                                   random_state=104,
#                                   test_size=0.25,
#                                   shuffle=True)

PCA on X_TRAIN only

In [15]:
cols2 = X_train.columns.difference(['ID'])

In [16]:
pca = PCA(n_components=10)

In [17]:
components_train = pca.fit_transform(X_train[cols2])

In [18]:
#principals = pd.DataFrame(data = components_train
#             , columns = ['pc1', 'pc2','pc3'])

principals = pd.DataFrame(data = components_train
             , columns = ['pc1', 'pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10'])

In [19]:
principals.head(1000)

,pc1,pc2,pc3,pc4,pc5,pc6,pc7,pc8,pc9,pc10
0,9.137606,3.992624,5.313656,1.815054,1.239565,-0.236095,0.678436,-1.902288,0.299220,1.124389
1,0.660523,8.809487,-2.806859,-3.162294,-2.495055,0.428763,-0.450727,1.933679,0.274963,-0.179984
2,-3.120217,3.510732,-4.046220,3.069565,2.526491,-0.616903,1.032870,-2.280891,-1.096935,0.884470
3,11.739705,-4.266337,-2.394055,-5.932022,4.164177,-0.966758,-3.634244,-0.322203,1.883445,-0.828690
4,7.579160,-4.174814,-0.693523,0.917455,-1.275536,0.818160,0.557236,-0.024350,1.024609,0.876682
...,...,...,...,...,...,...,...,...,...,...
669,-5.326057,4.486397,-3.898512,-3.103799,-1.806828,-4.866359,-0.006970,-0.208125,1.823698,0.254405
670,5.441308,1.871607,3.568035,-1.505565,2.868699,-0.383075,-1.532316,-1.162000,0.967816,3.331742
671,-8.777148,-2.666535,2.358829,-0.225779,2.609216,-0.903643,-0.156162,1.981844,1.469950,-0.734358
672,7.632551,-2.605374,0.197421,1.296811,-2.283297,1.637423,-1.426559,-0.005703,-0.275602,3.185529


In [20]:
print('Explained variability per principal component: {}'.format(pca.explained_variance_ratio_))


Explained variability per principal component: [0.48343758 0.1434075  0.0623262  0.05740259 0.04436615 0.02468838
 0.02388025 0.01803921 0.01576423 0.01322479]


In [ ]:
#DO A PLOT OF PCAs:  Do later

## MODEL #1:  NOW TRY A LOGISTIC REGRESSION ON THIS SCALED, PCA'd DATA

In [21]:
clf = LogisticRegression(random_state=0).fit(components_train, y_train)

In [22]:
y_pred = clf.predict(components_train)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,

In [23]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.95


In [24]:
clf.score(components_train, y_train)

0.9465875370919882

In [ ]:
#now run Scaler, PCA on X_test --> then test

In [25]:
cols = X_test.columns.difference(['ID', 'label'])

In [26]:
X_test[cols] = sc.transform(X_test[cols])

In [27]:
cols2 = X_test.columns.difference(['ID'])

In [28]:
components_test = pca.transform(X_test[cols2])

In [29]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1])

In [30]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.91


In [31]:
clf.score(components_test, y_test)

0.9100346020761245

In [32]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[157,  13],
       [ 13, 106]])

In [33]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.89'

In [34]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.89'

In [35]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.89'

MODEL #2:  SVM

In [ ]:
#use previous same 'sc' scaler and 'pca' transformations from train!!!

In [49]:
clf = svm.SVC(probability=True)

In [50]:
clf.fit(components_train, y_train)

SVC(probability=True)

In [51]:
y_pred = clf.predict(components_train)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,

In [52]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.98


In [53]:
clf.score(components_train, y_train)

0.9821958456973294

In [ ]:
#now run on test

In [54]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1])

In [55]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.99


In [56]:
clf.score(components_test, y_test)

0.986159169550173

In [57]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[167,   3],
       [  1, 118]])

In [58]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.98'

In [59]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.99'

In [60]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.98'

In [61]:
#get probability of SVM predictions
probs = clf.predict_proba(components_test)

In [62]:
print(probs)

[[1.23788575e-07 9.99999876e-01]
 [9.94602906e-01 5.39709374e-03]
 [9.94402832e-01 5.59716786e-03]
 [9.93359839e-01 6.64016089e-03]
 [9.89648289e-01 1.03517114e-02]
 [9.93093930e-01 6.90607007e-03]
 [9.86902958e-01 1.30970420e-02]
 [9.35706244e-01 6.42937564e-02]
 [9.76220877e-01 2.37791227e-02]
 [3.11770489e-07 9.99999688e-01]
 [2.77356484e-01 7.22643516e-01]
 [8.29307874e-03 9.91706921e-01]
 [9.79176581e-01 2.08234189e-02]
 [2.91636816e-02 9.70836318e-01]
 [2.68231200e-03 9.97317688e-01]
 [2.18079626e-01 7.81920374e-01]
 [1.52933101e-02 9.84706690e-01]
 [9.93266990e-01 6.73300993e-03]
 [9.93329661e-01 6.67033903e-03]
 [2.18244239e-08 9.99999978e-01]
 [9.93270364e-01 6.72963591e-03]
 [9.89377781e-01 1.06222190e-02]
 [4.67754857e-02 9.53224514e-01]
 [9.93798178e-01 6.20182153e-03]
 [5.19291452e-03 9.94807085e-01]
 [6.97703036e-03 9.93022970e-01]
 [7.78677168e-06 9.99992213e-01]
 [9.97520025e-01 2.47997497e-03]
 [9.93374993e-01 6.62500736e-03]
 [4.50183830e-01 5.49816170e-01]
 [2.915362

In [63]:
print(type(probs))

<class 'numpy.ndarray'>


In [67]:
print(probs.ndim)

2


In [66]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [68]:
probsdf.to_csv("svm_1.csv")

NOW RUN ON SUPPLIED TEST

In [ ]:
#1. sc on Test (transform only)
#2. pca on Test (transform only)
#3. run model on Test (predict only)
#4. run predict_proba on predictions
#5. export everything to csv's