IMPORT LIBRARIES

In [303]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score, recall_score,f1_score,roc_curve, roc_auc_score
from sklearn import svm
import csv

In [304]:
np.random.seed(187)

LOAD DATA

In [305]:
df = pd.read_csv('Train.csv')

In [225]:
df.head()

,ID,lon,lat,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,48.203643,40.090329,0,-23.328630,-16.733172,1599,1897,4129,4075,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,49.022098,39.829817,0,-18.638613,-10.334208,1907,2090,2953,3059,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,48.752963,39.764330,0,-21.356376,-14.257931,1355,1719,6722,6528,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,48.788806,39.770708,0,-20.289892,-9.187885,1504,1657,2093,2040,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,48.195468,39.857486,0,-19.046569,-14.159119,1357,1740,4905,4796,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972


In [226]:
#print(df.head(10))

EDA and STATS:  Done in R, ande in Python too

PREPROCESSING

In [306]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [228]:
df1.head()

,ID,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,re1_01,re2_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,0,-23.328630,-16.733172,1599,1897,4129,4075,2456,3594,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,0,-18.638613,-10.334208,1907,2090,2953,3059,2662,2777,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,0,-21.356376,-14.257931,1355,1719,6722,6528,2324,5405,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,0,-20.289892,-9.187885,1504,1657,2093,2040,1902,1914,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,0,-19.046569,-14.159119,1357,1740,4905,4796,2409,4150,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972


MORE EDA FIRST

In [229]:
#determine variable types
df1.dtypes

ID              str
label         int64
VH_01       float64
VV_01       float64
blue_01       int64
             ...   
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 146, dtype: object

In [307]:
#change label to category (same as factor in R)
df1['label']= df1['label'].astype("category")

In [308]:
df1.dtypes

ID               str
label       category
VH_01        float64
VV_01        float64
blue_01        int64
              ...   
re2_12         int64
re3_12         int64
red_12         int64
swir1_12       int64
swir2_12       int64
Length: 146, dtype: object

## Propsed Steps from here:
 Train Test Split of Train.csv

 StandardScaler on this 'train' data

 PCA on Scaled

 Modeling with this PCA

 Confusion Matrix/F1Score/AUC of model

 Run Model on this 'test' data

 Check multiple model types

 Then run on Test.csv and submit!



BACK TO PREPROCESSING

In [ ]:
#Train Test Split on df1

In [309]:
#first define
X = df1.drop(['label'], axis=1)
y = df1['label']

In [310]:
#Changed test_size to 'None'
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=None, random_state=187)

In [311]:
# except label, take all columns
cols = X_train.columns.difference(['ID', 'label'])

In [312]:
#STANDARDSCALER

sc = StandardScaler()

# normalise only selected columns
X_train[cols] = sc.fit_transform(X_train[cols])

In [313]:
print(X_train)

               ID     VH_01     VV_01   blue_01  green_01    nir_01   nira_01  \
452  ID_TR_4T60PL -1.103139 -1.677825 -0.943514 -1.040636 -1.162400 -1.209931   
482  ID_TR_XJ37C9 -0.430000  0.198043  0.856687  0.750678  0.454522  0.424746   
116  ID_TR_X7PTX6  1.226559  1.035255  0.001970 -0.077658  0.212103  0.581904   
864  ID_TR_D32LX2 -1.589752 -1.168219  0.977709  0.326265 -0.683533 -0.727743   
826  ID_TR_4K7BPG  0.111961  0.452741  1.083603  1.005326  0.499901  0.435462   
..            ...       ...       ...       ...       ...       ...       ...   
650  ID_TR_RMHRCN  0.011811  0.611885  1.321865  1.871713  1.556751  1.573664   
79   ID_TR_P6VZ41 -0.634322 -0.622814 -0.478336 -0.449385  0.804417  0.809306   
466  ID_TR_OT8HLJ -0.594349 -2.010015 -1.204468 -0.888433 -0.725330 -0.981338   
286  ID_TR_9V20YA -0.623276  0.593801 -0.803583 -0.835747 -0.266764 -0.056251   
619  ID_TR_Q6WW8Y  1.726328  1.393837 -0.538847 -0.464020 -0.000461 -0.082444   

       re1_01    re2_01    

PCA on X_train (and save for re-use on X_test)

In [ ]:
#start with test train split

#X= df1.drop['label']
#y=df1['label']

#need to make sure i get the variables to include in X and y correc, what about ID?


In [ ]:
#X_train, X_test,
#y_train, y_test = train_test_split(X,y ,
#                                   random_state=104,
#                                   test_size=0.25,
#                                   shuffle=True)

PCA on X_TRAIN only

In [314]:
cols2 = X_train.columns.difference(['ID'])

In [315]:
pca = PCA(n_components=20)

In [316]:
components_train = pca.fit_transform(X_train[cols2])

In [317]:
#principals = pd.DataFrame(data = components_train
#             , columns = ['pc1', 'pc2','pc3'])

principals = pd.DataFrame(data = components_train
             , columns = ['pc1', 'pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10', 'pc11', 'pc12','pc13','pc14','pc15','pc16','pc17','pc18','pc19','pc20'])

In [318]:
principals.head(1000)

,pc1,pc2,pc3,pc4,pc5,pc6,pc7,pc8,pc9,pc10,pc11,pc12,pc13,pc14,pc15,pc16,pc17,pc18,pc19,pc20
0,-14.696327,-6.265170,-0.363836,-0.867818,0.967680,0.047057,-0.427232,-0.608422,0.853882,1.768926,0.249773,-1.523557,0.769761,-0.495847,-0.047358,-0.603222,-0.386922,-0.237875,0.140223,-0.133721
1,2.163371,8.344093,1.716784,-7.259704,-4.058077,5.127921,-5.790070,1.369829,2.265012,-1.091152,0.195987,4.482638,-0.570111,0.004607,2.214177,1.284038,3.359767,-2.094154,0.590269,-1.270359
2,10.400029,-4.292985,-1.270526,2.028634,-2.467309,-1.161052,-1.337716,-1.188531,0.967874,-0.571780,-0.196629,0.080701,-0.786913,-0.342331,-0.387412,0.321515,0.556411,-0.613328,0.415597,0.436420
3,-4.363045,4.065335,4.406607,-1.704145,-4.574089,1.359443,-0.732663,0.129210,-0.225847,-1.903653,1.291192,-3.205233,0.738459,0.371082,-1.078695,0.788351,-0.136350,0.011619,-1.212787,0.732969
4,-3.492664,4.006611,-3.097932,-0.142786,1.446309,2.803156,1.284381,-2.307215,-1.232884,-1.438142,1.227865,-1.359600,-0.358226,2.017755,0.226395,1.213463,-0.825011,1.235686,0.200067,-0.209157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,-5.356157,4.424793,-3.699849,-3.329041,-1.805529,-4.847155,-0.507619,-0.685449,1.882996,0.225014,-0.133364,0.962470,-0.443604,1.561426,-1.201471,0.096993,-0.278202,0.134044,0.172986,-1.884625
718,5.392905,1.932205,3.658904,-1.201576,3.034332,-0.238379,-1.320175,-1.508095,0.669331,3.374902,0.528126,-1.282104,0.003300,-0.275132,0.815704,0.295450,-0.219683,-0.433149,0.133936,0.478540
719,-8.795555,-2.691869,2.279473,0.042853,2.684758,-0.875406,-0.455825,1.755133,1.759088,-0.772232,1.052722,0.448115,-0.757693,1.948791,0.888632,-0.867718,1.034013,0.218039,-0.825504,-0.881885
720,7.573139,-2.550383,0.275691,1.134986,-2.272887,1.757405,-1.129780,-0.005655,-0.418598,3.348998,-1.209102,-0.158084,0.311013,0.054166,1.331766,-0.186395,0.491030,-1.193839,-1.624813,-0.767806


In [319]:
print('Explained variability per principal component: {}'.format(pca.explained_variance_ratio_))


Explained variability per principal component: [0.48329017 0.14279037 0.06147777 0.05819935 0.0446613  0.02455194
 0.02407878 0.01819871 0.01576678 0.01317331 0.01123447 0.01050298
 0.0075812  0.00700027 0.00644733 0.00551921 0.00465591 0.00388717
 0.00383491 0.00333597]


In [ ]:
#DO A PLOT OF PCAs:  Do later

## MODEL #1:  NOW TRY A LOGISTIC REGRESSION ON THIS SCALED, PCA'd DATA

In [243]:
clf = LogisticRegression(random_state=0).fit(components_train, y_train)

In [244]:
y_pred = clf.predict(components_train)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,

In [245]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.98


In [246]:
clf.score(components_train, y_train)

0.9778393351800554

In [ ]:
#now run Scaler, PCA on X_test --> then test

In [247]:
cols = X_test.columns.difference(['ID', 'label'])

In [248]:
X_test[cols] = sc.transform(X_test[cols])

In [249]:
cols2 = X_test.columns.difference(['ID'])

In [250]:
components_test = pca.transform(X_test[cols2])

In [251]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [252]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.96


In [253]:
clf.score(components_test, y_test)

0.9585062240663901

In [254]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[135,   4],
       [  6,  96]])

In [255]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.96'

In [256]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.94'

In [257]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.95'

## MODEL #2:  SVM

In [ ]:
#use previous same 'sc' scaler and 'pca' transformations from train!!!

In [258]:
clf = svm.SVC(probability=True)

In [259]:
clf.fit(components_train, y_train)

C:\Users\fikramulla\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(


,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide <scores_probabilities>`...deprecated:: 1.9 The `probability` parameter is deprecated and will be removed in 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`.",True
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [260]:
y_pred = clf.predict(components_train)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,

In [261]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.99


In [262]:
clf.score(components_train, y_train)

0.9889196675900277

In [209]:
#now run on test

In [263]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [264]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.99


In [265]:
clf.score(components_test, y_test)

0.991701244813278

In [266]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[137,   2],
       [  0, 102]])

In [267]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.98'

In [268]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 1.0'

In [269]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.99'

In [270]:
#get probability of SVM predictions
probs = clf.predict_proba(components_test)

In [271]:
print(probs)

[[1.16386463e-08 9.99999988e-01]
 [9.97147262e-01 2.85273814e-03]
 [9.96946907e-01 3.05309331e-03]
 [9.92302116e-01 7.69788415e-03]
 [9.89264875e-01 1.07351247e-02]
 [9.93502215e-01 6.49778537e-03]
 [9.92116446e-01 7.88355384e-03]
 [9.92387966e-01 7.61203360e-03]
 [9.73663756e-01 2.63362441e-02]
 [7.60640340e-08 9.99999924e-01]
 [7.52665141e-02 9.24733486e-01]
 [7.49504295e-03 9.92504957e-01]
 [9.84862842e-01 1.51371575e-02]
 [5.42518229e-02 9.45748177e-01]
 [1.30515018e-07 9.99999869e-01]
 [8.06163631e-03 9.91938364e-01]
 [2.76941531e-03 9.97230585e-01]
 [9.95045602e-01 4.95439767e-03]
 [9.92531790e-01 7.46821023e-03]
 [2.35445553e-07 9.99999765e-01]
 [9.91477664e-01 8.52233579e-03]
 [9.88450470e-01 1.15495304e-02]
 [7.77565990e-03 9.92224340e-01]
 [9.90155333e-01 9.84466744e-03]
 [1.09492833e-05 9.99989051e-01]
 [1.87152897e-02 9.81284710e-01]
 [4.97653197e-07 9.99999502e-01]
 [9.98318406e-01 1.68159423e-03]
 [9.94319820e-01 5.68017972e-03]
 [3.34100389e-01 6.65899611e-01]
 [2.664190

In [49]:
print(type(probs))

<class 'numpy.ndarray'>


In [50]:
print(probs.ndim)

2


In [111]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [52]:
probsdf.to_csv("svm_1.csv")

GETTING THE CSV OUTPUT FOR SUBMITTED FORMAT

In [ ]:
#1. sc on Test (transform only)
#2. pca on Test (transform only)
#3. run model on Test (predict only)
#4. run predict_proba on predictions
#5. somehow only select high probability column
#6. export everything to csv's

In [56]:
# trying #5 first to make my life easier
probsdf.head()

,0,1
0,5.728762e-08,1.000000
1,9.943784e-01,0.005622
2,9.941647e-01,0.005835
3,9.930476e-01,0.006952
4,9.890405e-01,0.010960


In [60]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)

In [61]:
probsdf.head()

,0,1,max_val
0,5.728762e-08,1.000000,1.000000
1,9.943784e-01,0.005622,0.994378
2,9.941647e-01,0.005835,0.994165
3,9.930476e-01,0.006952,0.993048
4,9.890405e-01,0.010960,0.989040


In [68]:
probmax = probsdf['max_val']

In [71]:
probmax.head()

0    1.000000
1    0.994378
2    0.994165
3    0.993048
4    0.989040
Name: max_val, dtype: float64

In [74]:
probmax2 = pd.DataFrame(probmax)

In [75]:
probmax2.head()

,max_val
0,1.000000
1,0.994378
2,0.994165
3,0.993048
4,0.989040


In [86]:
#great that worked!, now select the 'max_val' column and append to your prediction dataframe/csv
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [87]:
preddf.head(15)

,pred
0,1
1,0
2,0
3,0
4,0
5,0
6,0
7,0
8,0
9,1


In [88]:
#now combine probmax2 and add it to preddf
final1 = pd.concat([preddf, probmax2], axis=1)

In [89]:
final1.head(15)

,pred,max_val
0,1,1.000000
1,0,0.994378
2,0,0.994165
3,0,0.993048
4,0,0.989040
5,0,0.992762
6,0,0.986052
7,0,0.929118
8,0,0.974302
9,1,1.000000


In [90]:
final1.to_csv("final.csv")

## NOW RUN ON SUPPLIED TEST

In [272]:
df = pd.read_csv('Test.csv')

In [273]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [274]:
df1.dtypes

ID              str
VH_01       float64
VV_01       float64
blue_01       int64
green_01      int64
             ...   
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 145, dtype: object

In [275]:
#ok, it only has ID, no problem
cols = df1.columns.difference(['ID'])

In [276]:
df1[cols] = sc.transform(df1[cols])

In [277]:
cols2 = df1.columns.difference(['ID'])

In [278]:
components_test = pca.transform(df1[cols2])

In [279]:
y_pred = clf.predict(components_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [280]:
length = len(y_pred)
print(length)  # Output: 858 is correct for 'Test.csv'

858


In [281]:
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [282]:
preddf.head()

,pred
0,0
1,0
2,0
3,0
4,0


In [283]:
probs = clf.predict_proba(components_test)

In [284]:
print(probs)

[[9.96106685e-01 3.89331503e-03]
 [9.81550319e-01 1.84496815e-02]
 [9.55612500e-01 4.43874996e-02]
 ...
 [1.73839514e-05 9.99982616e-01]
 [3.53792181e-03 9.96462078e-01]
 [2.17251771e-02 9.78274823e-01]]


In [285]:
length = len(probs)
print(length)  # Output: 858 is correct for 'Test.csv'

858


In [286]:
print(probs.ndim)

2


In [287]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [288]:
probsdf.head()

,0,1
0,0.996107,0.003893
1,0.981550,0.018450
2,0.955613,0.044387
3,0.996102,0.003898
4,0.957029,0.042971


In [289]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)
probsdf.head()

,0,1,max_val
0,0.996107,0.003893,0.996107
1,0.981550,0.018450,0.981550
2,0.955613,0.044387,0.955613
3,0.996102,0.003898,0.996102
4,0.957029,0.042971,0.957029


In [290]:
probmax = probsdf['max_val']

In [291]:
probmax2 = pd.DataFrame(probmax)

In [292]:
probmax2.head()

,max_val
0,0.996107
1,0.981550
2,0.955613
3,0.996102
4,0.957029


In [296]:
#now combine probmax2 and add it to preddf
model4 = pd.concat([preddf, probmax2], axis=1)

In [297]:
model4.head(15)

,pred,max_val
0,0,0.996107
1,0,0.981550
2,0,0.955613
3,0,0.996102
4,0,0.957029
5,0,0.871608
6,0,0.833012
7,0,0.666146
8,0,0.986956
9,0,0.942657


In [298]:
model4.to_csv("model4_svm_alltrain_pca20.csv")

## TRY A NEURAL NETWORK

In [329]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.neural_network import MLPClassifier

In [330]:
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)

In [331]:
mlp.fit(components_train, y_train)

,"hidden_layer_sizes hidden_layer_sizes: array-like of shape(n_layers - 2,), default=(100,)The ith element represents the number of neurons in the ithhidden layer.","(8, ...)"
,"max_iter max_iter: int, default=200Maximum number of iterations. The solver iterates until convergence(determined by 'tol') or this number of iterations. For stochasticsolvers ('sgd', 'adam'), note that this determines the number of epochs(how many times each data point will be used), not the number ofgradient steps.",500
,"activation activation: {'identity', 'logistic', 'tanh', 'relu'}, default='relu'Activation function for the hidden layer.- 'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x- 'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).- 'tanh', the hyperbolic tan function, returns f(x) = tanh(x).- 'relu', the rectified linear unit function, returns f(x) = max(0, x)",'relu'
,"solver solver: {'lbfgs', 'sgd', 'adam'}, default='adam'The solver for weight optimization.- 'lbfgs' is an optimizer in the family of quasi-Newton methods.- 'sgd' refers to stochastic gradient descent.- 'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy BaFor a comparison between Adam optimizer and SGD, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_training_curves.py`.Note: The default solver 'adam' works pretty well on relativelylarge datasets (with thousands of training samples or more) in terms ofboth training time and validation score.For small datasets, however, 'lbfgs' can converge faster and performbetter.",'adam'
,"alpha alpha: float, default=0.0001Strength of the L2 regularization term. The L2 regularization termis divided by the sample size when added to the loss.For an example usage and visualization of varying regularization, see:ref:`sphx_glr_auto_examples_neural_networks_plot_mlp_alpha.py`.",0.0001
,"batch_size batch_size: int, default='auto'Size of minibatches for stochastic optimizers.If the solver is 'lbfgs', the classifier will not use minibatch.When set to ""auto"", `batch_size=min(200, n_samples)`.",'auto'
,"learning_rate learning_rate: {'constant', 'invscaling', 'adaptive'}, default='constant'Learning rate schedule for weight updates.- 'constant' is a constant learning rate given by 'learning_rate_init'.- 'invscaling' gradually decreases the learning rate at each time step 't' using an inverse scaling exponent of 'power_t'. effective_learning_rate = learning_rate_init / pow(t, power_t)- 'adaptive' keeps the learning rate constant to 'learning_rate_init' as long as training loss keeps decreasing. Each time two consecutive epochs fail to decrease training loss by at least tol, or fail to increase validation score by at least tol if 'early_stopping' is on, the current learning rate is divided by 5.Only used when ``solver='sgd'``.",'constant'
,"learning_rate_init learning_rate_init: float, default=0.001The initial learning rate used. It controls the step-sizein updating the weights. Only used when solver='sgd' or 'adam'.",0.001
,"power_t power_t: float, default=0.5The exponent for inverse scaling learning rate.It is used in updating effective learning rate when the learning_rateis set to 'invscaling'. Only used when solver='sgd'.",0.5
,"shuffle shuffle: bool, default=TrueWhether to shuffle samples in each iteration. Only used whensolver='sgd' or 'adam'.",True
,"random_state random_state: int, RandomState instance, default=NoneDetermines random number generation for weights and biasinitialization, train-test split if early stopping is used, and batchsampling when solver='sgd' or 'adam'.Pass an int for reproducible results across multiple function calls.See :term:`Glossary <random_state>`.",None


In [332]:
y_pred = mlp.predict(components_train)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,

In [333]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 1.0


In [334]:
mlp.score(components_train, y_train)

1.0

RUN ON SUPPLIED TEST

In [335]:
df = pd.read_csv('Test.csv')
df1 = df.drop(['lon', 'lat'], axis=1)

In [336]:
cols = df1.columns.difference(['ID'])

In [337]:
df1[cols] = sc.transform(df1[cols])

In [338]:
cols2 = df1.columns.difference(['ID'])

In [339]:
components_test = pca.transform(df1[cols2])

In [340]:
y_pred = mlp.predict(components_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [341]:
length = len(y_pred)
print(length)  # Output: 858 is correct for 'Test.csv'

858


In [342]:
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [343]:
probs = mlp.predict_proba(components_test)

In [344]:
length = len(probs)
print(length)  # Output: 858 is correct for 'Test.csv'

858


In [345]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [346]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)
probsdf.head()

,0,1,max_val
0,0.999996,3.838238e-06,0.999996
1,1.000000,2.160388e-07,1.000000
2,0.968529,3.147107e-02,0.968529
3,0.999998,1.702893e-06,0.999998
4,0.806157,1.938428e-01,0.806157


In [347]:
probmax = probsdf['max_val']

In [348]:
probmax2 = pd.DataFrame(probmax)

In [349]:
probmax2.head()

,max_val
0,0.999996
1,1.000000
2,0.968529
3,0.999998
4,0.806157


In [352]:
#now combine probmax2 and add it to preddf
model5 = pd.concat([preddf, probmax2], axis=1)

In [353]:
model5.head(15)

,pred,max_val
0,0,0.999996
1,0,1.000000
2,0,0.968529
3,0,0.999998
4,0,0.806157
5,0,0.976208
6,1,0.994531
7,1,0.996912
8,0,0.999996
9,0,0.983804


In [354]:
model5.to_csv("model5_mlpnn_alltrain_pca20.csv")