IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score, recall_score,f1_score,roc_curve, roc_auc_score
from sklearn import svm
import csv

In [2]:
np.random.seed(187)

LOAD DATA

In [3]:
df = pd.read_csv('Train.csv')

In [4]:
df.head()

,ID,lon,lat,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,48.203643,40.090329,0,-23.328630,-16.733172,1599,1897,4129,4075,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,49.022098,39.829817,0,-18.638613,-10.334208,1907,2090,2953,3059,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,48.752963,39.764330,0,-21.356376,-14.257931,1355,1719,6722,6528,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,48.788806,39.770708,0,-20.289892,-9.187885,1504,1657,2093,2040,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,48.195468,39.857486,0,-19.046569,-14.159119,1357,1740,4905,4796,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972


In [ ]:
#print(df.head(10))

EDA and STATS:  Done in R, ande in Python too

PREPROCESSING

In [5]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [6]:
df1.head()

,ID,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,re1_01,re2_01,...,blue_12,green_12,nir_12,nira_12,re1_12,re2_12,re3_12,red_12,swir1_12,swir2_12
0,ID_TR_XAJI0Y,0,-23.328630,-16.733172,1599,1897,4129,4075,2456,3594,...,1453,1720,3115,2754,2134,2452,2596,1772,3063,2569
1,ID_TR_6DPBHS,0,-18.638613,-10.334208,1907,2090,2953,3059,2662,2777,...,1930,2282,3508,3377,2831,3019,3097,2662,3470,2642
2,ID_TR_AHXTHV,0,-21.356376,-14.257931,1355,1719,6722,6528,2324,5405,...,1444,1770,4648,4575,2311,4207,4437,1493,3235,2304
3,ID_TR_3A3ZMF,0,-20.289892,-9.187885,1504,1657,2093,2040,1902,1914,...,1446,1534,2212,2187,1762,1856,1984,1718,2858,2456
4,ID_TR_8MDD4V,0,-19.046569,-14.159119,1357,1740,4905,4796,2409,4150,...,1237,1434,2781,2867,1888,2540,2713,1421,2583,1972


MORE EDA FIRST

In [7]:
#determine variable types
df1.dtypes

ID              str
label         int64
VH_01       float64
VV_01       float64
blue_01       int64
             ...   
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 146, dtype: object

In [8]:
#change label to category (same as factor in R)
df1['label']= df1['label'].astype("category")

In [9]:
df1.dtypes

ID               str
label       category
VH_01        float64
VV_01        float64
blue_01        int64
              ...   
re2_12         int64
re3_12         int64
red_12         int64
swir1_12       int64
swir2_12       int64
Length: 146, dtype: object

## Propsed Steps from here:
 Train Test Split of Train.csv

 StandardScaler on this 'train' data

 PCA on Scaled

 Modeling with this PCA

 Confusion Matrix/F1Score/AUC of model

 Run Model on this 'test' data

 Check multiple model types

 Then run on Test.csv and submit!



BACK TO PREPROCESSING

In [ ]:
#Train Test Split on df1

In [10]:
#first define
X = df1.drop(['label'], axis=1)
y = df1['label']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=187)

In [12]:
# except label, take all columns
cols = X_train.columns.difference(['ID', 'label'])

In [13]:
#STANDARDSCALER

sc = StandardScaler()

# normalise only selected columns
X_train[cols] = sc.fit_transform(X_train[cols])

In [14]:
print(X_train)

               ID     VH_01     VV_01   blue_01  green_01    nir_01   nira_01  \
410  ID_TR_K9QM3P  0.391338  0.459898  0.538248  0.177820  0.345993  0.451430   
819  ID_TR_NN16UX  0.076397  1.136580  1.728600  1.652411  0.820518  0.797256   
888  ID_TR_SQ0P82  0.742511  0.475065  0.977589  0.664522  0.238576  0.187045   
10   ID_TR_9XUY41  0.667970  0.039622  0.061357  0.186511  1.524043  1.717883   
221  ID_TR_NF313F  0.598050  0.652943 -0.073825 -0.329162  0.530137  0.616671   
..            ...       ...       ...       ...       ...       ...       ...   
650  ID_TR_RMHRCN  0.012720  0.610762  1.319299  1.855203  1.534667  1.558544   
79   ID_TR_P6VZ41 -0.637186 -0.628189 -0.468106 -0.442146  0.791008  0.800797   
466  ID_TR_OT8HLJ -0.596981 -2.020168 -1.189076 -0.876701 -0.721098 -0.974363   
286  ID_TR_9V20YA -0.626076  0.592615 -0.791040 -0.824555 -0.267820 -0.057276   
619  ID_TR_Q6WW8Y  1.737251  1.395407 -0.528186 -0.456631 -0.004589 -0.083242   

       re1_01    re2_01    

PCA on X_train (and save for re-use on X_test)

In [ ]:
#start with test train split

#X= df1.drop['label']
#y=df1['label']

#need to make sure i get the variables to include in X and y correc, what about ID?


In [ ]:
#X_train, X_test,
#y_train, y_test = train_test_split(X,y ,
#                                   random_state=104,
#                                   test_size=0.25,
#                                   shuffle=True)

PCA on X_TRAIN only

In [15]:
cols2 = X_train.columns.difference(['ID'])

In [16]:
pca = PCA(n_components=10)

In [17]:
components_train = pca.fit_transform(X_train[cols2])

In [18]:
#principals = pd.DataFrame(data = components_train
#             , columns = ['pc1', 'pc2','pc3'])

principals = pd.DataFrame(data = components_train
             , columns = ['pc1', 'pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10'])

In [19]:
principals.head(1000)

,pc1,pc2,pc3,pc4,pc5,pc6,pc7,pc8,pc9,pc10
0,9.137606,3.992624,5.313656,1.815054,1.239565,-0.236095,0.678436,-1.902288,0.299220,1.124389
1,0.660523,8.809487,-2.806859,-3.162294,-2.495055,0.428763,-0.450727,1.933679,0.274963,-0.179984
2,-3.120217,3.510732,-4.046220,3.069565,2.526491,-0.616903,1.032870,-2.280891,-1.096935,0.884470
3,11.739705,-4.266337,-2.394055,-5.932022,4.164177,-0.966758,-3.634244,-0.322203,1.883445,-0.828690
4,7.579160,-4.174814,-0.693523,0.917455,-1.275536,0.818160,0.557236,-0.024350,1.024609,0.876682
...,...,...,...,...,...,...,...,...,...,...
669,-5.326057,4.486397,-3.898512,-3.103799,-1.806828,-4.866359,-0.006970,-0.208125,1.823698,0.254405
670,5.441308,1.871607,3.568035,-1.505565,2.868699,-0.383075,-1.532316,-1.162000,0.967816,3.331742
671,-8.777148,-2.666535,2.358829,-0.225779,2.609216,-0.903643,-0.156162,1.981844,1.469950,-0.734358
672,7.632551,-2.605374,0.197421,1.296811,-2.283297,1.637423,-1.426559,-0.005703,-0.275602,3.185529


In [20]:
print('Explained variability per principal component: {}'.format(pca.explained_variance_ratio_))


Explained variability per principal component: [0.48343758 0.1434075  0.0623262  0.05740259 0.04436615 0.02468838
 0.02388025 0.01803921 0.01576423 0.01322479]


In [ ]:
#DO A PLOT OF PCAs:  Do later

## MODEL #1:  NOW TRY A LOGISTIC REGRESSION ON THIS SCALED, PCA'd DATA

In [21]:
clf = LogisticRegression(random_state=0).fit(components_train, y_train)

In [22]:
y_pred = clf.predict(components_train)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,

In [23]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.95


In [24]:
clf.score(components_train, y_train)

0.9465875370919882

In [ ]:
#now run Scaler, PCA on X_test --> then test

In [25]:
cols = X_test.columns.difference(['ID', 'label'])

In [26]:
X_test[cols] = sc.transform(X_test[cols])

In [27]:
cols2 = X_test.columns.difference(['ID'])

In [28]:
components_test = pca.transform(X_test[cols2])

In [29]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1])

In [30]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.91


In [31]:
clf.score(components_test, y_test)

0.9100346020761245

In [32]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[157,  13],
       [ 13, 106]])

In [33]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.89'

In [33]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.89'

In [34]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.89'

MODEL #2:  SVM

In [ ]:
#use previous same 'sc' scaler and 'pca' transformations from train!!!

In [35]:
clf = svm.SVC(probability=True)

In [36]:
clf.fit(components_train, y_train)

C:\Users\fikramulla\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(


,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide <scores_probabilities>`...deprecated:: 1.9 The `probability` parameter is deprecated and will be removed in 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`.",True
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [37]:
y_pred = clf.predict(components_train)
y_pred

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,

In [38]:
accuracy = accuracy_score(y_train, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.98


In [39]:
clf.score(components_train, y_train)

0.9821958456973294

In [ ]:
#now run on test

In [40]:
y_pred = clf.predict(components_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1])

In [41]:
accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy: {round(accuracy,2)}")

accuracy: 0.99


In [42]:
clf.score(components_test, y_test)

0.986159169550173

In [43]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[167,   3],
       [  1, 118]])

In [44]:
precision = precision_score(y_test, y_pred)
f"Precision: {round(precision,2)}"

'Precision: 0.98'

In [45]:
recall = recall_score(y_test, y_pred)
f"Recall: {round(recall,2)}"

'Recall: 0.99'

In [46]:
f1 = f1_score(y_test, y_pred)
f"f1 score: {round(f1,2)}"

'f1 score: 0.98'

In [47]:
#get probability of SVM predictions
probs = clf.predict_proba(components_test)

In [48]:
print(probs)

[[5.72876173e-08 9.99999943e-01]
 [9.94378419e-01 5.62158130e-03]
 [9.94164699e-01 5.83530061e-03]
 [9.93047619e-01 6.95238139e-03]
 [9.89040462e-01 1.09595382e-02]
 [9.92762089e-01 7.23791055e-03]
 [9.86052379e-01 1.39476213e-02]
 [9.29118338e-01 7.08816619e-02]
 [9.74301942e-01 2.56980580e-02]
 [1.47661476e-07 9.99999852e-01]
 [2.39848935e-01 7.60151065e-01]
 [6.20682881e-03 9.93793171e-01]
 [9.77568765e-01 2.24312348e-02]
 [2.26468090e-02 9.77353191e-01]
 [1.14562585e-05 9.99988544e-01]
 [1.85273959e-01 8.14726041e-01]
 [1.16444793e-02 9.88355521e-01]
 [9.92947951e-01 7.05204941e-03]
 [9.93015228e-01 6.98477206e-03]
 [9.66989690e-09 9.99999990e-01]
 [9.92951573e-01 7.04842699e-03]
 [9.88746825e-01 1.12531751e-02]
 [3.69105938e-02 9.63089406e-01]
 [9.93517672e-01 6.48232755e-03]
 [3.83795468e-03 9.96162045e-01]
 [5.19742528e-03 9.94802575e-01]
 [3.99670137e-06 9.99996003e-01]
 [9.97466779e-01 2.53322051e-03]
 [9.93063882e-01 6.93611825e-03]
 [4.06291893e-01 5.93708107e-01]
 [2.531155

In [49]:
print(type(probs))

<class 'numpy.ndarray'>


In [50]:
print(probs.ndim)

2


In [51]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [52]:
probsdf.to_csv("svm_1.csv")

NOW RUN ON SUPPLIED TEST

In [ ]:
#1. sc on Test (transform only)
#2. pca on Test (transform only)
#3. run model on Test (predict only)
#4. run predict_proba on predictions
#5. somehow only select high probability column
#6. export everything to csv's

In [56]:
# trying #5 first to make my life easier
probsdf.head()

,0,1
0,5.728762e-08,1.000000
1,9.943784e-01,0.005622
2,9.941647e-01,0.005835
3,9.930476e-01,0.006952
4,9.890405e-01,0.010960


In [60]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)

In [61]:
probsdf.head()

,0,1,max_val
0,5.728762e-08,1.000000,1.000000
1,9.943784e-01,0.005622,0.994378
2,9.941647e-01,0.005835,0.994165
3,9.930476e-01,0.006952,0.993048
4,9.890405e-01,0.010960,0.989040


In [68]:
probmax = probsdf['max_val']

In [71]:
probmax.head()

0    1.000000
1    0.994378
2    0.994165
3    0.993048
4    0.989040
Name: max_val, dtype: float64

In [74]:
probmax2 = pd.DataFrame(probmax)

In [75]:
probmax2.head()

,max_val
0,1.000000
1,0.994378
2,0.994165
3,0.993048
4,0.989040


In [86]:
#great that worked!, now select the 'max_val' column and append to your prediction dataframe/csv
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [87]:
preddf.head(15)

,pred
0,1
1,0
2,0
3,0
4,0
5,0
6,0
7,0
8,0
9,1


In [88]:
#now combine probmax2 and add it to preddf
final1 = pd.concat([preddf, probmax2], axis=1)

In [89]:
final1.head(15)

,pred,max_val
0,1,1.000000
1,0,0.994378
2,0,0.994165
3,0,0.993048
4,0,0.989040
5,0,0.992762
6,0,0.986052
7,0,0.929118
8,0,0.974302
9,1,1.000000


In [90]:
final1.to_csv("final.csv")

NOW RUN ON SUPPLIED TEST

In [102]:
df = pd.read_csv('Test.csv')

In [103]:
df1 = df.drop(['lon', 'lat'], axis=1)

In [104]:
df1.dtypes

ID              str
VH_01       float64
VV_01       float64
blue_01       int64
green_01      int64
             ...   
re2_12        int64
re3_12        int64
red_12        int64
swir1_12      int64
swir2_12      int64
Length: 145, dtype: object

In [105]:
#ok, it only has ID, no problem
cols = df1.columns.difference(['ID'])

In [106]:
df1[cols] = sc.transform(df1[cols])

In [107]:
cols2 = df1.columns.difference(['ID'])

In [108]:
components_test = pca.transform(df1[cols2])

In [109]:
y_pred = clf.predict(components_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [111]:
length = len(y_pred)
print(length)  # Output: 858 is correct for 'Test.csv'

858


In [116]:
preddf = pd.DataFrame(y_pred, columns=["pred"])

In [117]:
preddf.head()

,pred
0,0
1,0
2,0
3,0
4,0


In [112]:
probs = clf.predict_proba(components_test)

In [113]:
print(probs)

[[0.99472065 0.00527935]
 [0.97778904 0.02221096]
 [0.97565295 0.02434705]
 ...
 [0.01054246 0.98945754]
 [0.00447361 0.99552639]
 [0.01909744 0.98090256]]


In [114]:
length = len(probs)
print(length)  # Output: 858 is correct for 'Test.csv'

858


In [115]:
print(probs.ndim)

2


In [118]:
probsdf = pd.DataFrame(probs, columns=["0", "1"])

In [119]:
probsdf.head()

,0,1
0,0.994721,0.005279
1,0.977789,0.022211
2,0.975653,0.024347
3,0.995554,0.004446
4,0.956689,0.043311


In [120]:
probsdf['max_val'] = probsdf[['0', '1']].max(axis=1)
probsdf.head()

,0,1,max_val
0,0.994721,0.005279,0.994721
1,0.977789,0.022211,0.977789
2,0.975653,0.024347,0.975653
3,0.995554,0.004446,0.995554
4,0.956689,0.043311,0.956689


In [121]:
probmax = probsdf['max_val']

In [122]:
probmax2 = pd.DataFrame(probmax)

In [123]:
probmax2.head()

,max_val
0,0.994721
1,0.977789
2,0.975653
3,0.995554
4,0.956689


In [124]:
#now combine probmax2 and add it to preddf
model1 = pd.concat([preddf, probmax2], axis=1)

In [125]:
model1.head(15)

,pred,max_val
0,0,0.994721
1,0,0.977789
2,0,0.975653
3,0,0.995554
4,0,0.956689
5,0,0.890516
6,0,0.875861
7,0,0.703337
8,0,0.988236
9,0,0.964649


In [126]:
model1.to_csv("model1_svm.csv")